# Generated by Django 2.2.1 on 2019-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bitsid',
            field=models.CharField(max_length=20),
        ),
    ]
