# Generated by Django 2.2.1 on 2019-06-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190608_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('opt1', models.CharField(max_length=25)),
                ('opt2', models.CharField(max_length=25)),
                ('opt3', models.CharField(max_length=25)),
                ('opt4', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bitsid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
